// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID int64
	// can be negative or positive
	Amount    int64
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// must be positive
	Amount    int64
	CreatedAt time.Time
}

type User struct {
	Username          string `json:"username"`
	HashedPassword    string `json:"hashed_password"`
	FullName          string `json:"full_name"`
	Email             string `json:"email"`
	PasswordChangedAt time.Time  `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
